lambda: passlib whirlpool
	zip big-hash-lambda.zip -r .
	
passlib:
	pip3 install passlib -t .

whirlpool:
	pip3 install whirlpool -t .

clean:
	rm -f big-hash-lambda.zip 
	rm -rf ./passlib ./passlib-*
	rm -rf ./whirlpool ./Whirlpool-*
